### ISSUE TITLE
Complete modulization of configs

### ISSUE THREAD

**Issue by ViktorHy** [Clinical-Genomics-Lund/SomaticPanelPipeline#20]
Move configs out of modules and into config-modules

All resource allocation should go into: base_config.nf
1. Use withLabel 
2. Add labels to modules corresponding to a reasonable resource allocation

Subworkflow configs go into other modules:
1. Use withName
2. publishDirs go here for relevant processes
3. container allocations go here

For instance create_cnv_pon.nf has resource allocation put into it. Use base_config.nf labels to achieve this but keep publishdirs and containers.

**Comment by ramsainanduri** [comment]
On it
